---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    
    iperf_vms:
      children:
        iperf_client:
          hosts: {}
          vars:
            iperf_role: client
        
        iperf_servers:
          hosts: {}
          vars:
            iperf_role: server
    
    infrastructure:
      children:
        database_servers:
          hosts: {}
        
        grafana_servers:
          hosts: {}

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_pipelining: true
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_user: ubuntu
    ansible_ssh_timeout: 30
    ansible_command_timeout: 30