---
galaxy_info:
  author: Your Name
  description: iPerf3 setup and configuration role
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - networking
    - performance
    - testing
    - iperf

dependencies: []