---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"
  failed_when: false

- name: Install prerequisites
  include_tasks: prerequisites.yml
  tags: prerequisites

- name: Install iPerf3
  include_tasks: install.yml
  tags: install

- name: Configure iPerf3 server
  include_tasks: configure-server.yml
  when: iperf_role == 'server'
  tags: configure

- name: Configure iPerf3 client
  include_tasks: configure-client.yml
  when: iperf_role == 'client'
  tags: configure